/*
How many distinct terms are in the sequence generated by a^b for 2<=a<=100 and 2<=b<=100?

Answer  = 9183
Time Complexity = O(N^4)
*/

#include<math.h>
#include<stdio.h>
# define N 100

int main(){
    double arr[N*N]={0};// to stores a^b
    int index = 0;// index to array
    for(int a=2;a<=N;a++){
        for(int b=2;b<=N;b++){
            double v = b*log10(a);//apply log on a^b = blog(a) to reduce its value
            // arr[index++]= b*log10(a);
            int f = 0;
            for(int i=0;i<=index;i++){
                if(fabs(arr[i] - v) < 1e-10){// if v is present in array skip it
                    f = 1;
                    break;
                }
            }
            if(f==0)arr[index++]= v;//if v is not in array add it to array and increment index
        }
    }
    printf("%d",index);
}

