//How many distinct terms are in the sequence generated by a raised power b for 2<=a<=100
// and 
// ?2<=b<=100?

// for this purpose i calculated the power of all digittsstarting from 2 to  100
// and power also starting from 2 to 100.once i got the numbers
// i put them in an array named arr;then i used two loops in an array just to check 
// are there any duplicate elemnets in an array or not;
// if yes i used break statement and the other non unique _Readable_elements_i tracked the count of them


#include <stdio.h>

int main() {
    long long arr[9801];        
    long long index = 0;      

    for (long long base = 2; base <= 100; base++) {
        for (long long exponent = 2; exponent <= 100; exponent++) {
            long long result = 1;
            for (int i = 0; i < exponent; i++) {
                result *= base;
            }
            arr[index++] = result;
            printf(" %lld\n",result);
        }
    }


    long long uniqueCount = 0;

    for (long long i = 0; i < index; i++) {
        int isFlag = 1; 

        for (long long j = 0; j < i; j++) {
            if (arr[i] == arr[j]) {
                isFlag = 0;
                break;
            }
        }

        if (isFlag == 1) {
            uniqueCount++;
        }
    }

    printf("Unique numbers in array: %lld  \n", uniqueCount);

    return 0;
}
